[applyWithSchema] fail to validate the result
  args: [1 1]
  result: 'abc
  schema: (-> int? int? int?)
  target: (lambda (x y) 'abc)

  --> examples/tests/claim/claim-result.error.lisp:2:1
 1 | (claim my-add (-> int? int? int?))
 2 | (define (my-add x y) 'abc)
   | ~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 3 | 
 4 | (my-add 1 1)
[applyWithSchema] fail to validate an argument (due to the error above)
  args: [1 1]
  schema: (-> int? int? int?)
  target: (lambda (x y) 'abc)

  --> examples/tests/claim/claim-result.error.lisp:2:1
 1 | (claim my-add (-> int? int? int?))
 2 | (define (my-add x y) 'abc)
   | ~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 3 | 
 4 | (my-add 1 1)

